# week08/.github/workflows/frontend_ci.yml

name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  # e.g. nihal08.azurecr.io (store this in repo secrets as AZURE_CONTAINER_REGISTRY)
  ACR_LOGIN_SERVER: nihal08.azurecr.io
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Azure (needed if you later add az commands)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ Login to ACR using Docker credentials (no need to parse registry name)
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: nihal08.azurecr.io   # e.g. nihal08.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}               # ACR admin user
          password: ${{ secrets.ACR_PASSWORD }}               # ACR admin password

      - name: Build and Push Frontend Image
        run: |
          docker build -t $ACR_LOGIN_SERVER/frontend:latest ./frontend
          docker push $ACR_LOGIN_SERVER/frontend:latest

      - name: Logout from Azure
        if: always()
        run: az logout
